spring:
    application:
        name: USER-SERVICE
    datasource:
        url: jdbc:postgresql://localhost:5432/booklify
        username: postgres
        password: pgadmin
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    main:
        web-application-type: reactive
    session:
        jdbc:
            initialize-schema: always

server:
    port: 8081

management:
    server:
        port: 9091
    endpoints:
        web:
            exposure:
                include: "*"

logging:
    level:
        web: DEBUG

springdoc:
    swagger-ui:
        enabled: true
    api-docs:
        enabled: true
    show-actuator: true
    use-management-port: true