spring:
    application:
        name: "@project.artifactId@"
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: pgadmin
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
    main:
        web-application-type: servlet
#        allow-bean-definition-overriding: true

server:
    port: 8081

management:
    endpoints:
        web:
            exposure:
                include: "*"

logging:
    level:
        web: DEBUG

eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka/
        fetchRegistry: true
        register-with-eureka: true

springdoc:
    api-docs:
        enabled: true